// Run against the isolated local backend; requires Puppeteer and the backend face fixtures.
import { pathToFileURL } from 'node:url'
import path from 'node:path'
const { default: puppeteer } = await import(process.env.PUPPETEER_PATH ? pathToFileURL(process.env.PUPPETEER_PATH).href : 'puppeteer')
const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox'] })
const base = process.env.TEST_FRONTEND_URL || 'http://127.0.0.1:3000'
const face = path.resolve('backend/test_faces/face1.jpg')
const errors = []
const studentContext = await browser.createBrowserContext()
const adminContext = await browser.createBrowserContext()
const student = await studentContext.newPage()
const admin = await adminContext.newPage()
for (const page of [student, admin]) page.on('pageerror', e => errors.push(e.message))
async function click(page, label) {
  await page.waitForFunction(text => [...document.querySelectorAll('button')].some(b => b.textContent.trim() === text), {polling: 100}, label)
  await page.evaluate(text => [...document.querySelectorAll('button')].find(b => b.textContent.trim() === text).click(), label)
}
async function contains(page, text) { await page.waitForFunction(text => document.body.innerText.includes(text), {timeout: 20000, polling: 100}, text) }
async function fill(page, selector, value) { await page.waitForSelector(selector); await page.type(selector, value) }
try {
  await student.goto(base+'/register')
  if (await student.$('video,canvas')) throw new Error('Registration contains camera capture')
  const inputs = await student.$$('input')
  const id = Date.now()
  for (const [i, value] of ['Browser Student', `browser${id}@example.org`, `BROWSER${id}`, 'Password123', 'Password123'].entries()) await inputs[i].type(value)
  await click(student, 'Create Account / Sign Up')
  await student.waitForFunction(() => location.pathname === '/enroll', {polling: 100})
  await student.goto(base+'/vote')
  await student.waitForFunction(() => location.pathname === '/enroll', {polling: 100})
  await student.goto(base+'/login')
  await fill(student,'input[type=email]', `browser${id}@example.org`)
  await fill(student,'input[type=password]', 'Password123')
  await click(student,'Login')
  await contains(student,'Secure Face Enrollment')
  console.log('REGISTRATION: PASS\nEMAIL LOGIN: PASS\nENROLLMENT BYPASS BLOCKED: PASS')
  const upload = await student.$('input[type=file]:not([capture])')
  await upload.uploadFile(face)
  await student.waitForSelector('img[alt="Face preview"]')
  await contains(student,'Photo selected')
  if (!await student.$('input[capture=user]')) throw new Error('Native camera control missing')
  await click(student,'Enroll Face')
  await student.waitForFunction(() => location.pathname === '/dashboard', {timeout: 30000, polling: 100})
  await contains(student,'Election Dashboard')
  console.log('FACE ENROLLMENT: PASS')
  await admin.goto(base+'/login')
  await fill(admin,'input[type=email]','admin@example.org')
  await fill(admin,'input[type=password]','LocalTestingPassword')
  await click(admin,'Login')
  await contains(admin,'Admin Dashboard')
  await click(admin,'Elections')
  await fill(admin,'input[placeholder="Election name"]',`Browser election ${id}`)
  await fill(admin,'input[placeholder="Election description"]','Created through the real admin interface')
  await click(admin,'Create Election')
  await contains(admin,'Election created successfully.')
  await fill(admin,'input[placeholder="Position name"]','Browser position')
  await click(admin,'Add Position')
  await contains(admin,'Position added successfully.')
  await fill(admin,'input[placeholder="Candidate full name"]','Browser candidate')
  await fill(admin,'input[placeholder="Candidate CGPA"]','4.42')
  await fill(admin,'textarea','A manifesto stored in the database')
  await (await admin.$('input[type=file]')).uploadFile(face)
  await admin.waitForSelector('img[alt="Candidate photo preview"]')
  await click(admin,'Add Candidate')
  await contains(admin,'Candidate added successfully.')
  await click(admin,'Activate')
  await contains(admin,'Election marked as active.')
  await contains(student,'Browser candidate')
  await contains(student,'4.42')
  await student.waitForFunction(() => [...document.querySelectorAll('img')].some(img => img.src.includes('/uploads/candidates/') && img.complete && img.naturalWidth > 0), {polling: 100})
  console.log('ADMIN ELECTION CREATION: PASS\nCANDIDATE CREATION: PASS\nCANDIDATE IMAGE: PASS\nCANDIDATE CGPA: PASS\nSTUDENT DASHBOARD SYNC: PASS')
  await click(admin,'Edit Candidate')
  await admin.$eval('input[placeholder="Candidate CGPA"]', el => { el.focus(); el.select() })
  await admin.keyboard.type('4.33')
  await click(admin,'Save Candidate')
  await contains(student,'4.33')
  console.log('CANDIDATE UPDATE SYNC: PASS')
  await click(student,'Vote')
  await contains(student,'Browser candidate')
  await student.evaluate(() => [...document.querySelectorAll('h3')].find(el => el.textContent==='Browser candidate').parentElement.click())
  await click(student,'Review & Submit')
  await contains(student,'Review Your Selections')
  await (await student.$('input[type=file]')).uploadFile(face)
  await click(student,'Cast Secure Vote')
  await contains(student,'Vote cast successfully.')
  await click(admin,'Results')
  await contains(admin,'1 votes')
  console.log('VOTING: PASS\nRESULTS: PASS')
  await click(student,'Return to dashboard')
  await click(student,'Vote')
  await contains(student,'Browser candidate')
  await student.evaluate(() => [...document.querySelectorAll('h3')].find(el => el.textContent==='Browser candidate').parentElement.click())
  await click(student,'Review & Submit')
  await student.waitForSelector('input[type=file]')
  await (await student.$('input[type=file]')).uploadFile(face)
  await click(student,'Cast Secure Vote')
  await contains(student,'You have already voted in this election.')
  console.log('DOUBLE-VOTE PROTECTION: PASS')
  if (errors.length) throw new Error(errors.join('\n'))
} catch (e) {
  console.error('BROWSER TEST FAILED', e)
  console.error('STUDENT:', await student.evaluate(() => document.body.innerText))
  console.error('ADMIN:', await admin.evaluate(() => document.body.innerText))
  process.exitCode = 1
} finally { await browser.close() }
